"""System map generator — walks src/ and emits docs/MAP.md.

Parses each `src/*.py` via `ast`, extracts the module docstring's first line as
the glossary entry, and the static imports as graph edges. Internal imports
(siblings in `src/`) become edges between modules; known external imports
(litellm, anthropic, chromadb, etc.) become edges to a separate "external
services" cluster.

Run with `uv run python src/system_map.py` — overwrites `docs/MAP.md`.
"""

from __future__ import annotations

import ast
from pathlib import Path

SRC_DIR = Path(__file__).parent
DOCS_DIR = SRC_DIR.parent / "docs"
MAP_PATH = DOCS_DIR / "MAP.md"
HTML_PATH = DOCS_DIR / "MAP.html"

EXTERNAL_SERVICES: dict[str, str] = {
    "litellm": "OpenAI / Anthropic API (via LiteLLM)",
    "openai": "OpenAI API",
    "anthropic": "Anthropic API",
    "chromadb": "ChromaDB",
    "datasets": "HuggingFace Dataset",
    "huggingface_hub": "HuggingFace Hub",
    "gradio": "Gradio (UI)",
}

NO_DOCSTRING_SENTINEL = "(no description — add a module docstring)"


def parse_module(path: Path) -> tuple[str, list[str]]:
    """Return (first line of the module docstring, list of top-level imports)."""
    tree = ast.parse(path.read_text())
    docstring = ast.get_docstring(tree) or ""
    first_line = docstring.strip().split("\n", 1)[0].strip() if docstring else ""

    imports: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module:
            imports.append(node.module.split(".")[0])
        elif isinstance(node, ast.Import):
            for alias in node.names:
                imports.append(alias.name.split(".")[0])
    return first_line, imports


def _list_modules(src_dir: Path) -> list[str]:
    return sorted(p.stem for p in src_dir.glob("*.py") if not p.stem.startswith("_"))


def build_graph(src_dir: Path) -> dict:
    """Walk `src_dir`, parse each module, return modules / internal / external edges / glossary."""
    modules = _list_modules(src_dir)
    module_set = set(modules)

    internal_edges: list[tuple[str, str]] = []
    external_edges: list[tuple[str, str]] = []
    glossary: dict[str, str] = {}

    for m in modules:
        first_line, imports = parse_module(src_dir / f"{m}.py")
        glossary[m] = first_line or NO_DOCSTRING_SENTINEL
        for imp in imports:
            if imp == m:
                continue
            if imp in module_set:
                edge = (m, imp)
                if edge not in internal_edges:
                    internal_edges.append(edge)
            elif imp in EXTERNAL_SERVICES:
                edge = (m, EXTERNAL_SERVICES[imp])
                if edge not in external_edges:
                    external_edges.append(edge)

    return {
        "modules": modules,
        "internal_edges": internal_edges,
        "external_edges": external_edges,
        "glossary": glossary,
    }


def _emit_mermaid(graph: dict) -> str:
    lines = ["```mermaid", "graph LR"]
    for m in graph["modules"]:
        lines.append(f'  {m}["{m}.py"]')
    for service in sorted({label for _, label in graph["external_edges"]}):
        lines.append(f'  ext_{_slug(service)}(["{service}"])')
    for src, dst in graph["internal_edges"]:
        lines.append(f"  {src} --> {dst}")
    for src, label in graph["external_edges"]:
        lines.append(f"  {src} --> ext_{_slug(label)}")
    lines.append("```")
    return "\n".join(lines)


def _slug(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s)


def _emit_glossary(graph: dict) -> str:
    lines = ["| Module | Description |", "|---|---|"]
    for m in graph["modules"]:
        lines.append(f"| `{m}.py` | {graph['glossary'][m]} |")
    return "\n".join(lines)


def render(src_dir: Path) -> str:
    """Produce the full MAP.md content for `src_dir` as a single string."""
    graph = build_graph(src_dir)
    return (
        "# System Map\n\n"
        "Auto-generated by `src/system_map.py`. Do not edit by hand — re-run with "
        "`uv run python src/system_map.py` after touching modules in `src/`.\n\n"
        "Companion docs: [`CONTEXT.md`](../CONTEXT.md) (domain glossary), "
        "[`docs/adr/`](./adr/) (architectural decisions).\n\n"
        "## Module graph\n\n"
        + _emit_mermaid(graph)
        + "\n\n"
        "## Glossary\n\n"
        + _emit_glossary(graph)
        + "\n"
    )


def render_html(src_dir: Path) -> str:
    """Standalone HTML preview — Mermaid graph + glossary, rendered client-side via CDN."""
    graph = build_graph(src_dir)
    mermaid_block = "\n".join(_emit_mermaid(graph).splitlines()[1:-1])  # strip ``` fences
    glossary_rows = "".join(
        f'<tr><td><code>{m}.py</code></td><td>{graph["glossary"][m]}</td></tr>'
        for m in graph["modules"]
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Digital Twin — System Map</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif; padding: 2em; max-width: 1200px; margin: 0 auto; color: #1a1a1a; }}
    h1 {{ border-bottom: 2px solid #ddd; padding-bottom: 0.4em; }}
    h2 {{ margin-top: 2em; }}
    .mermaid {{ background: white; border: 1px solid #eee; padding: 1em; border-radius: 6px; min-height: 400px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 1em; }}
    th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; vertical-align: top; }}
    th {{ background: #f6f6f6; }}
    code {{ background: #f6f6f6; padding: 2px 6px; border-radius: 3px; font-family: ui-monospace, monospace; }}
    .meta {{ color: #666; font-size: 0.9em; }}
  </style>
</head>
<body>
  <h1>Digital Twin — System Map</h1>
  <p class="meta">Auto-generated from <code>src/*.py</code> imports + module docstrings. Refresh with <code>uv run python src/system_map.py</code>.</p>
  <h2>Module graph</h2>
  <pre class="mermaid">
{mermaid_block}
  </pre>
  <h2>Glossary</h2>
  <table>
    <tr><th>Module</th><th>Description</th></tr>
    {glossary_rows}
  </table>
  <script>mermaid.initialize({{ startOnLoad: true, theme: 'default', flowchart: {{ curve: 'basis' }} }});</script>
</body>
</html>
"""


def main() -> None:
    md = render(SRC_DIR)
    MAP_PATH.write_text(md)
    html = render_html(SRC_DIR)
    HTML_PATH.write_text(html)
    print(f"Wrote {MAP_PATH.relative_to(SRC_DIR.parent)} + {HTML_PATH.relative_to(SRC_DIR.parent)}")


if __name__ == "__main__":
    main()
